---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: cosmic-atomic
description: This is my personal OS image.
base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - "mkdir -p /var/roothome"
      - "dnf5 -y swap --repo='fedora' OpenCL-ICD-Loader ocl-icd"
      - "dnf5 config-manager addrepo --from-repofile='https://negativo17.org/repos/fedora-multimedia.repo'"
      - "dnf5 config-manager setopt fedora-multimedia.priority=90"
      - "mv /usr/etc/containers/policy.json /etc/containers/policy.json"
      
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
        - ublue-os/staging
    install:
      packages:
        - ublue-os-just
        - ublue-os-luks
        - ublue-os-signing
        - ublue-os-udev-rules
        - ublue-os-update-services
        - fedora-repos-archive
        - zstd
        - alsa-firmware
        - android-udev-rules
        - apr
        - apr-util
        - distrobox
        - fdk-aac
        - ffmpeg
        - ffmpeg-libs
        - ffmpegthumbnailer
        - flatpak-spawn
        - fuse
        - fzf
        - google-noto-sans-balinese-fonts
        - google-noto-sans-cjk-fonts
        - google-noto-sans-javanese-fonts
        - google-noto-sans-sundanese-fonts
        - grub2-tools-extra
        - heif-pixbuf-loader
        - htop
        - intel-vaapi-driver
        - just
        - libavcodec
        - libcamera
        - libcamera-gstreamer
        - libcamera-ipa
        - libheif
        - libcamera-tools
        - libfdk-aac
        - libimobiledevice-utils
        - libratbag-ratbagd
        - libva-utils
        - lshw
        - mesa-libxatracker
        - net-tools
        - nvme-cli
        - nvtop
        - openrgb-udev-rules
        - openssl
        - oversteer-udev
        - pam-u2f
        - pam_yubico
        - pamu2fcfg
        - pipewire-libs-extra
        - pipewire-plugin-libcamera
        - powerstat
        - smartmontools
        - solaar-udev
        - squashfs-tools
        - symlinks
        - tcpdump
        - tmux
        - traceroute
        - usbmuxd
        - vim
        - wireguard-tools
        - wl-clipboard
        - xhost
        - xorg-x11-xauth
        - yubikey-manager
    remove:
      packages:
        - fedora-flathub-remote
        - google-noto-sans-cjk-vf-fonts
        - default-fonts-cjk-sans
    replace:
      - from-repo: fedora-multimedia
        skip-unavailable: true
        packages:
          - intel-gmmlib
          - intel-mediasdk
          - intel-vpl-gpu-rt
          - libheif
          - libva
          - libva-intel-media-driver
          - mesa-dri-drivers
          - mesa-filesystem
          - mesa-libEGL
          - mesa-libGL
          - mesa-libgbm
          - mesa-va-drivers
          - mesa-vulkan-drivers
    
  - type: script
    scripts:
      - install-cosign.sh
      - finalize.sh

  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer
        - flatpak-system-update.timer
    user:
      enabled:
        - flatpak-user-update.timer
  
  - type: initramfs

  - type: signing
